export const PLANS = [
  {
    name: "Starter Plan",
    subtitle: "Best for testing",
    monthlyPrice: 0,
    annualPrice: 0,
    currency: "₹",
    buttonText: "Get Started",
    buttonVariant: "outlined",
    isPopular: false,
    isCurrentPlan: true,
    inheritLabel: null,
    features: [
      "1 Doctor Profile",
      "1 User Login",
      "Basic Scheduling",
      "Online Booking Page",
      "Email Confirmation",
      "Patient Database (Up to 300)",
    ],
  },
  {
    name: "Growth Plan",
    subtitle: "Best for active solo practice",
    monthlyPrice: 999,
    annualPrice: 799,
    currency: "₹",
    buttonText: "Choose Plan",
    buttonVariant: "outlined",
    isPopular: false,
    inheritLabel: "EVERYTHING IN STARTER +",
    features: [
      "Unlimited Patients",
      "SMS Confirmations",
      "Automated Reminders",
      "Google Calendar Sync",
      "Email Support",
    ],
  },
  {
    name: "Professional Plan",
    subtitle: "Best for private practice",
    monthlyPrice: 2499,
    annualPrice: 1999,
    currency: "₹",
    buttonText: "Choose Plan",
    buttonVariant: "solid",
    isPopular: true,
    inheritLabel: "EVERYTHING IN GROWTH +",
    features: [
      "WhatsApp Reminders",
      "Online Payments Integration",
      "Recurring Appointments",
      "Self-Reschedule Portal",
      "Priority Support",
    ],
  },
  {
    name: "Premium Plan",
    subtitle: "Digital clinic setup",
    monthlyPrice: 4999,
    annualPrice: 3999,
    currency: "₹",
    buttonText: "Choose Plan",
    buttonVariant: "outlined",
    isPopular: false,
    inheritLabel: "EVERYTHING IN PRO +",
    features: [
      "Telemedicine / Video Consultations",
      "Custom Branding",
      "API Access",
      "Advanced Analytics",
      "Dedicated Account Manager",
    ],
  },
];

export const COMPARISON_FEATURES = [
  {
    name: "Patient Database",
    starter: "Up to 300",
    growth: "Unlimited",
    professional: "Unlimited",
    premium: "Unlimited",
  },
  {
    name: "Reminders",
    starter: "Email Only",
    growth: "SMS & Email",
    professional: "WhatsApp & SMS",
    premium: "All Channels",
  },
  {
    name: "Calendar Sync",
    starter: null,
    growth: "Google Calendar",
    professional: "Advanced Sync",
    premium: "Advanced Sync",
  },
  {
    name: "Payments",
    starter: "Manual",
    growth: "Manual",
    professional: "Online Integrated",
    premium: "Online Integrated",
  },
  {
    name: "Telemedicine",
    starter: null,
    growth: null,
    professional: null,
    premium: "Yes (HD Video)",
    highlight: true,
  },
  {
    name: "Support",
    starter: "Community",
    growth: "Email",
    professional: "Priority",
    premium: "Dedicated Manager",
  },
];
